<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>promise 3</title>
    <script type="text/javascript" charset="utf-8">
// 在上例的基础上，对调两个promise的timeout时间，比较一下微妙的结果变化

var p1 = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error('fail')), 1000)
})

var p2 = new Promise(function (resolve, reject) {
  // 3秒时p2才开始进行resolve，p1在1秒时就已经reject了
  // p1 reject的时候，p2的resolve还没有接管p1，因此会得到一个uncaught的error
  // 但p2接管p1之后，它仍然会接管p1产生的error，因此p2的错误机制代码仍然会起作用（这里的效果同上例）
  setTimeout(() => resolve(p1), 3000)
})

var x = p2.then(result => {
    console.log("haha:")
    console.log(result)
}/*,
error => {
  console.log("error: ")
  console.log(error)
}*/).catch(error => { // 注释掉reject回调之后，将会在catch里捕获到error
    console.log("gotcha")
    console.log(error)
})

    </script>
  </head>
  <body>
    body
  </body>
</html>
